version: '2'
services:
  fluent-es:
    image: liangzh/fluent-kafka-es:feature_influxdb
    stdin_open: true
    tty: true
    ports:
    - 24224:24224/tcp
    external_links:
      - "${kafkabroker}:kafkabroker"
      - "${influxdb}:influxdb"