.catalog:
  name: fluentd
  version: "add influxdb"
  description: |
    fluentd
  questions:
    - variable: kafkabroker
      label: "kafka broker"
      type: "service"
      required: true
      description: |
        kafka broker
    - variable: influxdb
      label: "influxdb"
      type: "service"
      required: true
      description: |
        influxdb
  services:
    fluent-es:
      scala: 1