version: '2'
services:
  fluent-es:
    image: liangzh/fluent-kafka-es
    stdin_open: true
    tty: true
    ports:
    - 24224:24224/tcp
    external_links:
      - "${elasticsearch}:elasticsearch"
      - "${kafkabroker}:kafkabroker"
    labels:
      io.rancher.scheduler.global: 'true'
